name: Bug Report
description: Create a report to help us improve
labels: [bug]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
    validations:
      required: true
  - type: textarea
    id: xsd
    attributes:
      label: Relevant XSD snippet
      render: xml
  - type: textarea
    id: version
    attributes:
      label: Library version
      placeholder: v0.1.2
